---
framework: jest
postMerge: 
  pattern: 
    - './src/**/*.spec.ts'
preMerge:
  pattern:
    - './src/**/*.spec.ts'
preRun:
     command:
        - npm i
postRun:
     command:
        - node --version
parallelism: 1
version: 1.0
