---
framework: jest
postMerge: 
  pattern: 
    - './src/**/*.spec.ts'
  strategy: 
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - './src/**/*.spec.ts'
preRun:
     command:
        - npm i
postRun:
     command:
        - node --version
version: 2.1
